version: '3.8'
services:
  web:
    restart: always
    build: ./Robots
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Robots/:/usr/src/app/
    ports:
      - "8080:8000"
    env_file:
      - ./Robots/.env
    depends_on:
      - postgres
      - redis
  celery:
    build: ./Robots
    command: celery -A Robots worker -l INFO
    volumes:
      - ./Robots/:/usr/src/app/
    depends_on:
      - web
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6319:6379"
  postgres:
    restart: always
    container_name: robots_postgres
    image: postgres:13-alpine
    env_file:
      - ./Robots/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5455:5432"
  django_tests:
    build: ./Robots
    command: python manage.py test
    volumes:
      - ./Robots/:/usr/src/app/
    depends_on:
      - web