# Generated by Django 5.0 on 2024-01-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RobotsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
