# Generated by Django 5.0 on 2024-01-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RobotsAPI', '0003_rename_rob_model_robot_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=200, verbose_name='модель'),
        ),
    ]
