# Generated by Django 5.0 on 2024-01-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RobotsAPI', '0004_alter_robot_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waiting_List',
            new_name='WaitingList',
        ),
    ]
