# Generated by Django 5.0 on 2024-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RobotsAPI', '0005_rename_waiting_list_waitinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='файл статистики')),
            ],
        ),
    ]
