# Generated by Django 5.0 on 2024-01-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RobotsAPI', '0006_statisticsfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticsfile',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='statisticsfile',
            name='title',
            field=models.CharField(default='file', max_length=200, verbose_name='file'),
        ),
    ]
