# Generated by Django 5.0 on 2024-01-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RobotsAPI', '0007_alter_statisticsfile_options_statisticsfile_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticsFile',
        ),
    ]
