# Generated by Django 5.0 on 2024-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RobotsAPI', '0009_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='наличие'),
        ),
    ]
